# Development Dockerfile - Flutter web with hot reload
FROM ghcr.io/cirruslabs/flutter:3.24.0

WORKDIR /app

COPY pubspec.yaml pubspec.lock* ./
RUN flutter pub get

COPY . .

EXPOSE 8080

CMD ["flutter", "run", "-d", "web-server", "--web-port=8080", "--web-hostname=0.0.0.0"]
