#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────
# PCOS One-Command Installer
# Usage: curl -fsSL https://raw.githubusercontent.com/dayashimoga/pcos/main/install.sh | bash
# Or:    bash install.sh [--dev] [--no-monitoring] [--port PORT]
# ─────────────────────────────────────────────────────────
set -euo pipefail

# ─── Colors ─────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log()    { echo -e "${BLUE}[PCOS]${NC} $*"; }
ok()     { echo -e "${GREEN}  ✓${NC} $*"; }
warn()   { echo -e "${YELLOW}  ⚠${NC} $*"; }
err()    { echo -e "${RED}  ✗${NC} $*"; }
header() { echo -e "\n${CYAN}${BOLD}═══ $* ═══${NC}\n"; }

# ─── Arguments ──────────────────────────────────────────
DEV_MODE=false
MONITORING=true
PORT=8080
INSTALL_DIR="${PCOS_INSTALL_DIR:-$HOME/pcos}"

while [[ $# -gt 0 ]]; do
  case $1 in
    --dev)          DEV_MODE=true; shift ;;
    --no-monitoring) MONITORING=false; shift ;;
    --port)         PORT="$2"; shift 2 ;;
    --dir)          INSTALL_DIR="$2"; shift 2 ;;
    -h|--help)
      echo "PCOS Installer"
      echo ""
      echo "Usage: install.sh [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --dev            Use development compose file"
      echo "  --no-monitoring  Skip Grafana/Prometheus setup"
      echo "  --port PORT      Set API port (default: 8080)"
      echo "  --dir PATH       Installation directory (default: ~/pcos)"
      echo "  -h, --help       Show this help"
      exit 0
      ;;
    *) err "Unknown option: $1"; exit 1 ;;
  esac
done

# ─── Banner ─────────────────────────────────────────────
echo ""
echo -e "${CYAN}${BOLD}"
echo "  ╔═══════════════════════════════════════╗"
echo "  ║     ☁  PCOS - Personal Cloud OS      ║"
echo "  ║         One-Command Installer         ║"
echo "  ╚═══════════════════════════════════════╝"
echo -e "${NC}"

# ─── 1. Prerequisites Check ────────────────────────────
header "Checking Prerequisites"

check_command() {
  if command -v "$1" &>/dev/null; then
    ok "$1 found ($(command -v "$1"))"
    return 0
  else
    err "$1 not found"
    return 1
  fi
}

MISSING=0
check_command docker || MISSING=1
check_command docker || MISSING=1
check_command git    || MISSING=1

# Check Docker Compose (v2 or v1)
if docker compose version &>/dev/null 2>&1; then
  COMPOSE_CMD="docker compose"
  ok "Docker Compose v2 found"
elif command -v docker-compose &>/dev/null; then
  COMPOSE_CMD="docker-compose"
  ok "Docker Compose v1 found"
else
  err "Docker Compose not found"
  MISSING=1
fi

# Check Docker running
if docker info &>/dev/null 2>&1; then
  ok "Docker daemon is running"
else
  err "Docker daemon is not running"
  echo "  Please start Docker and try again."
  exit 1
fi

if [[ $MISSING -eq 1 ]]; then
  echo ""
  err "Missing prerequisites. Please install them and try again."
  echo "  Docker: https://docs.docker.com/get-docker/"
  echo "  Git:    https://git-scm.com/downloads"
  exit 1
fi

# ─── 2. Clone/Update Repository ────────────────────────
header "Setting Up PCOS"

if [[ -d "$INSTALL_DIR/.git" ]]; then
  log "Updating existing installation at $INSTALL_DIR"
  cd "$INSTALL_DIR"
  git pull --ff-only origin main 2>/dev/null || warn "Could not auto-update (manual merge may be needed)"
  ok "Repository updated"
else
  log "Cloning PCOS to $INSTALL_DIR"
  git clone https://github.com/dayashimoga/pcos.git "$INSTALL_DIR" 2>/dev/null
  cd "$INSTALL_DIR"
  ok "Repository cloned"
fi

# ─── 3. Generate Environment ───────────────────────────
header "Configuring Environment"

if [[ -f .env ]]; then
  warn ".env file already exists — keeping existing configuration"
else
  log "Generating secure environment configuration..."
  JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | base64 | tr -d '\n/+=')
  DB_PASSWORD=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | base64 | tr -d '\n/+=')

  cat > .env <<EOF
# Generated by PCOS Installer — $(date -u +%Y-%m-%dT%H:%M:%SZ)
PCOS_JWT_SECRET=${JWT_SECRET}
POSTGRES_PASSWORD=${DB_PASSWORD}
POSTGRES_USER=pcos
POSTGRES_DB=pcos
PCOS_DATABASE__URL=postgresql://pcos:${DB_PASSWORD}@postgres:5432/pcos
PCOS_SERVER__HOST=0.0.0.0
PCOS_SERVER__PORT=${PORT}
PCOS_STORAGE__BASE_PATH=/data/pcos/storage
PCOS_STORAGE__MAX_UPLOAD_SIZE_MB=10240
PCOS_AI__URL=http://ollama:11434
PCOS_AI__MODEL=llama3.1
PCOS_REDIS__URL=redis://redis:6379
PCOS_CORS_ORIGINS=*
RUST_LOG=pcos=info,tower_http=info,sqlx=warn
GRAFANA_ADMIN_PASSWORD=admin
EOF

  ok "Environment file generated with secure random secrets"
fi

# ─── 4. Start Services ─────────────────────────────────
header "Starting Services"

COMPOSE_FILE="docker-compose.yml"
if [[ "$DEV_MODE" == true ]]; then
  COMPOSE_FILE="docker-compose.dev.yml"
  log "Using development compose file"
fi

log "Pulling latest images..."
$COMPOSE_CMD -f "$COMPOSE_FILE" pull 2>/dev/null || warn "Some images may need to be built"

log "Starting PCOS services..."
$COMPOSE_CMD -f "$COMPOSE_FILE" up -d 2>/dev/null

ok "Services starting..."

# ─── 5. Wait for Health ────────────────────────────────
header "Waiting for Services"

log "Waiting for PCOS backend to become healthy..."
RETRIES=30
for i in $(seq 1 $RETRIES); do
  if curl -sf "http://localhost:${PORT}/health" >/dev/null 2>&1; then
    ok "Backend is healthy!"
    break
  fi
  if [[ $i -eq $RETRIES ]]; then
    warn "Backend not responding after ${RETRIES}s — it may still be starting"
    warn "Check logs with: $COMPOSE_CMD logs backend"
  fi
  sleep 1
done

# ─── 6. Summary ─────────────────────────────────────────
header "Installation Complete"

echo -e "${GREEN}${BOLD}"
echo "  ╔═══════════════════════════════════════════════════╗"
echo "  ║  ☁  PCOS is installed and running!               ║"
echo "  ╚═══════════════════════════════════════════════════╝"
echo -e "${NC}"
echo ""
echo -e "  ${BOLD}Web UI:${NC}        http://localhost:${PORT}"
echo -e "  ${BOLD}API:${NC}           http://localhost:${PORT}/api/v1"
echo -e "  ${BOLD}Health:${NC}        http://localhost:${PORT}/health"
echo -e "  ${BOLD}Setup Wizard:${NC}  http://localhost:${PORT}/setup"
if [[ "$MONITORING" == true ]]; then
  echo -e "  ${BOLD}Grafana:${NC}       http://localhost:3000 (admin/admin)"
fi
echo ""
echo -e "  ${BOLD}Manage:${NC}"
echo "    $COMPOSE_CMD logs -f         # View logs"
echo "    $COMPOSE_CMD ps              # Check status"
echo "    $COMPOSE_CMD down            # Stop services"
echo "    $COMPOSE_CMD up -d           # Start services"
echo ""
echo -e "  ${BOLD}Next Steps:${NC}"
echo "    1. Open http://localhost:${PORT}/setup"
echo "    2. Create your admin account"
echo "    3. Start uploading files!"
echo ""
ok "Installation directory: $INSTALL_DIR"
echo ""
